#1 xss対策
Ryutarosan/ccgup-ec pull request #3
Opened 2019-06-30 00:35 UTC by Ryutarosan

# 概要
xss対策

# 変更内容
- h関数の追加

# 影響範囲
- HTMLタグがタグとしてではなく文字として反映される
- admin.php(販売者画面)
- cart.php(カート画面)
- finish.php(購入完了画面)
- login.php(ログイン画面)
- top.php(トップ画面)
- output_message.php(各画面で利用される完了、エラーメッセージ)
- output_navber.php(画面上部のバー)
# 動作要件
- なし

# 補足
- なし

2019-06-30 00:39 UTC, thisprodigiousgeek commented
コメントです。

2019-07-01 09:26 UTC, Ryutarosan commented
概要
xss対策

変更内容
h関数の追加

影響範囲
HTMLタグがタグとしてではなく文字として反映される
admin.php(販売者画面)
cart.php(カート画面)
finish.php(購入完了画面)
login.php(ログイン画面)
top.php(トップ画面)
output_message.php(各画面で利用される完了、エラーメッセージ)
output_navber.php(画面上部のバー)

動作要件
なし

補足
なし

2019-07-01 14:10 UTC, Ryutarosan commented
概要
sqlインジェクション対策

変更内容
sql文をプレースホルダー を使用する形に書き直す
$params配列にプレースホルダーにバインドする変数を詰め込む
db_updateの際に$paramsを第三引数として渡す

影響範囲

admin.php(販売者画面)
cart.php(カート画面)
finish.php(購入完了画面)
login.php(ログイン画面)
top.php(トップ画面)


動作要件
なし

補足
なし

2019-07-01 23:56 UTC, thisprodigiousgeek requested changes
ほぼ完成していらっしゃいますね！
output_message.phpだけ、問題がありました。
確認してみてくださいね！

2019-07-01 23:56 UTC, thisprodigiousgeek commented on lib/view/element/output_message.php
> +		echo h(implode('<br>', $response['error_msg']));
ここだけ、ちょっと確認しておきましょう。
管理ページで複数のエラーメッセージが表示される場合、
何が起きるかチェックしてみてくださいね！

2019-07-02 01:30 UTC, thisprodigiousgeek commented
こちらでオッケーです！マージさせていただきます。お疲れ様でした！

2019-07-02 01:45 UTC, merged